### ISSUE TITLE
#12 Neusaglašenost ER dijagrama i dizajna baze

### ISSUE THREAD

**Issue by emilisic1** [SoftverInzenjeringETFSA/SI2016_TIM8#12]
Komponenta: DIZAJN-Tim8-final.pdf

Commit ID:  94e9111

Opis problema: U dizajnu sistema-ER dijagram navedena je tabela "OdjavaPoložaja" (http://pokit.org/get/?20ee87558366e60cdfdb0b0b08790c32.jpg), koja nije implementirana u bazi podataka (http://pokit.org/get/?3cac40958929bf3a0bcbcae03527bd49.jpg). 

Niz koraka:
-Otvaranje dokumenta "DIZAJN-Tim8-final.pdf", sekcija 2.3. ER dijagram
-Otvaranje baze podataka na phpMyAdmin
-Uočavanje razlika u dizajnu i implementaciji

**Comment by etfgunner** [comment]
Tabela OdjavaPolozaja je bila bespotrebna(nije imala nikakvu funkciju), pa uz dogovor sa klijentom, ista je izbačena.
