### ISSUE TITLE
#4 Odjava patrola/radara nije implementirana u skladu sa koracima definisanim u SRSu

### ISSUE THREAD

**Issue by emilisic1** [SoftverInzenjeringETFSA/SI2016_TIM8#4]
Komponenta: PrijavaPolozajaService.java

Commit ID: 8d779e5

Opis problema: Prema SRSu (funkcionalni zahtjev 3.2.6.) korisniku je omogućeno da prijavi odsustvo patrole/radara na prethodno prijavljenoj lokaciji, dok je admin taj koji ima privilegiju da istu ukloni sa liste (funkcionalni zahtjev 3.2.10), ukoliko je lokacija prijavljena kao netačna dovoljan broj puta. Također, uklanjanje lokacije bi trebalo biti omogućeno automatski, ukoliko brojač netačnih prijava dostigne određenu vrijednost. Trenutno, u aplikaciji je omogućeno da obični korisnik odjavi patrolu, pri čemu se ona briše iz baze, što nije u skladu s prethodno opisanim koracima (http://pokit.org/get/?896a4de1a7ba7ee9a6c38b9cc74ae644.jpg). Također, nije implementiran brojač netačnih prijava, koji bi automatski uklonio prijavu s liste.

Koraci koji vode do greške:
- Pokrenuti aplikaciju na localhost: 4200
- Ukoliko korisnik nema kreiran korisnički račun potrebno ga je kreirati, a u suprotnom potrebno se samo prijaviti na sistem kao obični korisnik
- Odabirom opcije "Pregled patrola" otvara se lista prijavljenih patrola/radara
- Klikom na dugme "Odjavi patrolu" prijavljena patrola se briše s liste te iz baze

**Comment by etfgunner** [comment]
Kako u SRS-u nije unaprijed definisana vrijednost brojača nakon kojeg bi patrola bila odjavljena, odlučili smo se da to bude za brojač=1, tako da je ovo ok.
