### ISSUE TITLE
Ne postoji mogućnost blokiranja zlonamjernih korisnika 

### ISSUE THREAD

**Issue by berina17131** [SoftverInzenjeringETFSA/SI2016_TIM8#9]
Komponenta: prikazkorisnika.hbs

Commit: 5f67ea2

Opis problema: Administratorima nije omogućeno da, ukoliko je korisnik nepouzdan (ima veliki broj lažnih prijava),  blokira istog. Prema SRS-u (sekcija  2.3.3. i 2.3.4) administratori radi sigurnosti drugih korisnika moraju imati uvid u pouzdanost korisnika i mogućnost blokiranja istog ako je potrebno.
(http://pokit.org/get/?0c8328766fa1882ebfc6fc228f188a12.jpg)

Opis koraka:
- Pokrenuti aplikaciju na localhost:4200
- Odabrati opciju 'Prijavi se' (prijaviti se kao superadmin ili admin)
- Odabrati opciju na meniju 'Korisnici'
- Prikaz liste bez opcije za blokiranje korisnika

**Comment by etfgunner** [comment]
Fixed
